### ISSUE TITLE
thursday morning session peer review

### ISSUE THREAD

**Issue by DevaWinner** [suthish777/Personal-portfolio#5]

**Comment by manzitresor** [comment]
Your code are good nothing to change

**Comment by Zafron047** [comment]
- [ ] No linters error found
- [ ] Descriptive commits
- [ ] Git flow was correct

It's time to merge. 😄

**Comment by DevaWinner** [comment]
Your code is amazing. Great job

**Comment by suthish777** [comment]
Thanks for the review review guys.
