### ISSUE TITLE
Merging not done yet

### ISSUE THREAD

**Issue by MariamOsman11** [suthish777/Personal-portfolio#7]
You have done amazing job here! I suggest you merge all your branch to your main

**Comment by suthish777** [comment]
Thank you for the comments.

**Comment by Abbas-Aljuaifari** [comment]
good job so far your CODE IS CLEAN and you got the branch to be merged well done!!
![](https://media.giphy.com/media/8yZuEb7q6dlyP3L3cL/giphy.gif)
